# 1. Install Library

In [37]:
!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)

In [38]:
from google_play_scraper import reviews, Sort
import pandas as pd

In [39]:
result, continuation_token = reviews(
    'blibli.mobile.commerce',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=1200
)

In [40]:
df = pd.DataFrame(result)

df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,0927d4ad-73c1-4e4f-bb2a-c8f19704981f,Indrio Purnomo,https://play-lh.googleusercontent.com/a-/ALV-U...,Blibli offers a premium shopping experience wi...,5,0,14.0.1,2026-06-27 16:14:49,Hi Indrio Purnomo Thank you so much for your a...,2026-06-27 16:35:16,14.0.1
1,9226457d-f631-4054-ac13-4401a791fa21,balwin dar,https://play-lh.googleusercontent.com/a/ACg8oc...,"eror terus tidak dapat mendaftar atau login,to...",1,0,14.0.1,2026-06-27 15:21:17,Halo Kak Balwin Dar mohon maaf terkait kendala...,2026-06-27 15:38:54,14.0.1
2,1f1efecf-3d8c-446a-a504-06f8d02468f7,Afrizal Julianto,https://play-lh.googleusercontent.com/a/ACg8oc...,baru nyoba nanti kalo cepat pengiriman nya tam...,4,0,14.0.1,2026-06-27 14:35:12,"Hi kak, terima kasih sudah mencoba Blibli ditu...",2026-06-28 15:22:32,14.0.1
3,9a5c6f53-a1b1-497c-857c-533387270ca9,Pakai Kode 3HZWYJMN5 Dapat 5juta,https://play-lh.googleusercontent.com/a/ACg8oc...,€ Alhamdulillah dapat saldo di shopeepay 5juta...,5,0,14.0.1,2026-06-27 12:11:50,None,NaT,14.0.1
4,142771d6-44ee-40f0-ab43-ea3a947d3e48,Yufa Agista,https://play-lh.googleusercontent.com/a-/ALV-U...,"mantap, saya suka interface nya",5,0,13.9.0,2026-06-27 12:06:37,None,NaT,13.9.0

In [41]:
df = df[['content', 'score']]

df.head()

                                             content  score
0  Blibli offers a premium shopping experience wi...      5
1  eror terus tidak dapat mendaftar atau login,to...      1
2  baru nyoba nanti kalo cepat pengiriman nya tam...      4
3  € Alhamdulillah dapat saldo di shopeepay 5juta...      5
4                    mantap, saya suka interface nya      5

In [42]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [43]:
df.to_csv(
    "/content/drive/MyDrive/hasil_scraping_blibli.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset berhasil disimpan!")

Dataset berhasil disimpan!